### ISSUE TITLE
An Android apk could be done with "ionic cordova build android --prod --release"

### ISSUE THREAD

**Issue by happy2discover** [ionic-team/ionic-starter-super#138]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

    Error: 
    Type CardsPage in .../src/pages/cards/cards.ts is part of the declarations of 2 modules: CardsPageModule in .../src/pages/cards/card.module.ts and CardsPageModule in .../src/pages/cards/cards.module.ts! 

    Please consider moving CardsPage in .../src/pages/cards/cards.ts to a higher module that imports CardsPageModule in .../src/pages/cards/card.module.ts and CardsPageModule in .../src/pages/cards/cards.module.ts. 

    You can also create a new NgModule that exports and includes CardsPage in .../src/pages/cards/cards.ts then import that NgModule in CardsPageModule in .../src/pages/cards/card.module.ts and CardsPageModule in .../src/pages/cards/cards.module.ts.

    at syntaxError (...\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at CompileMetadataResolver._addTypeToModule (...\node_modules\@angular\compiler\bundles\compiler.umd.js:15728:31)
    at ...\node_modules\@angular\compiler\bundles\compiler.umd.js:15616:27
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (...\node_modules\@angular\compiler\bundles\compiler.umd.js:15607:54)
    at addNgModule (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24403:58)
    at ...\node_modules\@angular\compiler\bundles\compiler.umd.js:24414:14
    at Array.forEach (<anonymous>)
    at _createNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24413:26)
    at analyzeNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24288:14)
 
**Expected behavior:**

An Android apk could be done.

**Steps to reproduce:**

```
ionic cordova build android --prod --release
```

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v8.6.0
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : pro
```

**Comment by janpio** [comment]
Any changes to the code done before trying to build?

**Comment by happy2discover** [comment]
@janpio No Changes. An Android apk could be done with "ionic cordova build android"

**Comment by janpio** [comment]
Is it `--prod` or `--release` that is causing the problem?

**Comment by happy2discover** [comment]
@janpio It is `--prod`. Build successful with `--release`.

**Comment by janpio** [comment]
Does it work for iOS?

**Comment by happy2discover** [comment]
@janpio The same error as Android.

**Comment by happy2discover** [comment]
@janpio I might find out the reason. There is an unnecessary "card.module.ts". I deleted it and got "BUILD SUCCESSFUL".
